// <auto-generated />
using Final_project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Final_project.Migrations.MssqladminOptionsDb
{
    [DbContext(typeof(MssqladminOptionsDbContext))]
    [Migration("20231011220632_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Final_project.Models.AdminOptions.BlogSection", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("photo");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("PK__BlogSect__3213E83FBC314320");

                    b.ToTable("BlogSection", (string)null);
                });

            modelBuilder.Entity("Final_project.Models.AdminOptions.ContactSection", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("PK__ContactS__3213E83F3821F8F0");

                    b.ToTable("ContactSection", (string)null);
                });

            modelBuilder.Entity("Final_project.Models.AdminOptions.FooterSection", b =>
                {
                    b.Property<int>("ContactsId")
                        .HasColumnType("int")
                        .HasColumnName("contactsId");

                    b.Property<string>("ContactsPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contactsPath");

                    b.Property<string>("LocationPhoto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("locationPhoto");

                    b.Property<string>("TextAbout")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("textAbout");

                    b.ToTable("FooterSection", (string)null);
                });

            modelBuilder.Entity("Final_project.Models.AdminOptions.HeaderSection", b =>
                {
                    b.Property<string>("Header")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MainInfo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.ToTable("HeaderSection", (string)null);
                });

            modelBuilder.Entity("Final_project.Models.AdminOptions.ProjectsSection", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("header");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("photo");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("PK__Projects__3213E83F80FFA181");

                    b.ToTable("ProjectsSection", (string)null);
                });

            modelBuilder.Entity("Final_project.Models.AdminOptions.ServicesSection", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("HeaderOfService")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("PK__Services__3213E83FF5D9647E");

                    b.ToTable("ServicesSection", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
